In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
original = pd.read_csv("/content/original_dataset.csv", index_col=False)

In [3]:
equivalent = original[original['RelationType']== 'Equivalent'][['RelationType','Governor','Dependent']]
equivalent = equivalent.rename({'RelationType':'relation', 'Governor': 'head', 'Dependent': 'tail'}, axis=1)
equivalent['relation'] = equivalent['relation'].replace({"Equivalent": "__label__Equivalent"})

In [4]:
equivalent.head(5)

,relation,head,tail
6,__label__Equivalent,Cuba is not lost,"I look at Cuba today, I believe that we are fo..."
9,__label__Equivalent,"I look at Cuba today, I believe that we are fo...",We think that's pretty good progress
10,__label__Equivalent,Cuba is not lost,We think that's pretty good progress
11,__label__Equivalent,In the first place I've never suggested that C...,In my speech last night I indicated that I tho...
26,__label__Equivalent,There isn't any question but that we will defe...,There isn't any question but that we will defe...

In [5]:
equivalent.head()

,relation,head,tail
6,__label__Equivalent,Cuba is not lost,"I look at Cuba today, I believe that we are fo..."
9,__label__Equivalent,"I look at Cuba today, I believe that we are fo...",We think that's pretty good progress
10,__label__Equivalent,Cuba is not lost,We think that's pretty good progress
11,__label__Equivalent,In the first place I've never suggested that C...,In my speech last night I indicated that I tho...
26,__label__Equivalent,There isn't any question but that we will defe...,There isn't any question but that we will defe...

In [6]:
train, test = train_test_split(equivalent,
								   test_size=0.2,
								   random_state=42,
								   stratify=equivalent['relation'])

In [7]:
test, val = train_test_split(test, test_size=0.5, random_state=42, stratify=test['relation'])

In [8]:
train = train.dropna().drop_duplicates().reset_index(drop=True)
test = test.dropna().drop_duplicates().reset_index(drop=True)
val = val.dropna().drop_duplicates().reset_index(drop=True)

In [9]:
test_df = pd.read_csv("/content/test_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])
train_df = pd.read_csv("/content/train_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])
dev_df = pd.read_csv("/content/dev_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])

In [10]:
test_df = pd.concat([test_df, test], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)
train_df = pd.concat([train_df, train], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)
dev_df = pd.concat([dev_df, val], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)

In [11]:
test_df = test_df[test_df['relation']!='__label__noRel']
train_df = train_df[train_df['relation']!='__label__noRel']
dev_df = dev_df[dev_df['relation']!='__label__noRel']

In [12]:
test_df['relation'].value_counts()

__label__Support       2167
__label__Attack         384
__label__Equivalent      46
Name: relation, dtype: int64

In [13]:
test_df.to_csv("/content/test_relations_new.tsv", sep="\t", index=False)
train_df.to_csv("/content/train_relations_new.tsv", sep="\t", index=False)
dev_df.to_csv("/content/dev_relations_new.tsv", sep="\t", index=False)

In [14]:
dataset = pd.concat([train_df, test_df], axis=0)

In [15]:
dataset = pd.concat([dataset, dev_df], axis=0)

In [16]:
dataset = dataset.dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)

In [17]:
dataset.head(5)

,relation,head,tail
0,__label__Support,this administration has begun to transform the...,Al Gore and I are committed to continuing this...
1,__label__Support,"if we want to talk about oil company profits, ...",here's the problem: If we are giving them to o...
2,__label__Support,about half as much chance to own a house.,I'm not satisfied until every American enjoys ...
3,__label__Support,it may not work,"if it doesn't work, then we have strengthened ..."
4,__label__Attack,you can't be for school choice,You attended a private school for some time in...

In [18]:
dataset.to_csv("/content/relations_new.tsv", sep="\t", index=False)