In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [11]:
original = pd.read_csv("/content/original_dataset.csv", index_col=False)

In [12]:
equivalent = original[original['RelationType']== 'Equivalent'][['RelationType','Governor','Dependent']]
equivalent = equivalent.rename({'RelationType':'relation', 'Governor': 'head', 'Dependent': 'tail'}, axis=1)
equivalent['relation'] = equivalent['relation'].replace({"Equivalent": "__label__Equivalent"})

In [13]:
equivalent.head(5)

,relation,head,tail
6,__label__Equivalent,Cuba is not lost,"I look at Cuba today, I believe that we are fo..."
9,__label__Equivalent,"I look at Cuba today, I believe that we are fo...",We think that's pretty good progress
10,__label__Equivalent,Cuba is not lost,We think that's pretty good progress
11,__label__Equivalent,In the first place I've never suggested that C...,In my speech last night I indicated that I tho...
26,__label__Equivalent,There isn't any question but that we will defe...,There isn't any question but that we will defe...

In [14]:
equivalent.head()

,relation,head,tail
6,__label__Equivalent,Cuba is not lost,"I look at Cuba today, I believe that we are fo..."
9,__label__Equivalent,"I look at Cuba today, I believe that we are fo...",We think that's pretty good progress
10,__label__Equivalent,Cuba is not lost,We think that's pretty good progress
11,__label__Equivalent,In the first place I've never suggested that C...,In my speech last night I indicated that I tho...
26,__label__Equivalent,There isn't any question but that we will defe...,There isn't any question but that we will defe...

In [15]:
train, test = train_test_split(equivalent,
								   test_size=0.2,
								   random_state=42,
								   stratify=equivalent['relation'])

In [16]:
test, val = train_test_split(test, test_size=0.5, random_state=42, stratify=test['relation'])

In [17]:
train = train.dropna().drop_duplicates().reset_index(drop=True)
test = test.dropna().drop_duplicates().reset_index(drop=True)
val = val.dropna().drop_duplicates().reset_index(drop=True)

In [18]:
test_df = pd.read_csv("/content/test_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])
train_df = pd.read_csv("/content/train_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])
dev_df = pd.read_csv("/content/dev_relations.tsv", index_col=False, sep="\t", names=['relation', 'head', 'tail'])

train_df[['head', 'relation', 'tail']].to_csv("/content/train_relations_new.tsv", sep="\t", index=False)
test_df[['head', 'relation', 'tail']].to_csv("/content/test_relations_new.tsv", sep="\t", index=False)
dev_df[['head', 'relation', 'tail']].to_csv("/content/dev_relations_new.tsv", sep="\t", index=False)

In [19]:
test_df = pd.concat([test_df, test], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)
train_df = pd.concat([train_df, train], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)
dev_df = pd.concat([dev_df, val], axis=0).dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)

In [20]:
test_df = test_df[test_df['relation']!='__label__noRel']
train_df = train_df[train_df['relation']!='__label__noRel']
dev_df = dev_df[dev_df['relation']!='__label__noRel']

In [21]:
test_df['relation'].value_counts()

__label__Support       2167
__label__Attack         384
__label__Equivalent      71
Name: relation, dtype: int64

In [22]:
test_df.to_csv("/content/original_test_relations.tsv", sep="\t", index=False)
train_df.to_csv("/content/original_train_relations.tsv", sep="\t", index=False)
dev_df.to_csv("/content/original_dev_relations.tsv", sep="\t", index=False)

In [23]:
dataset = pd.concat([train_df, test_df], axis=0)

In [24]:
dataset = pd.concat([dataset, dev_df], axis=0)

In [25]:
dataset = dataset.dropna().drop_duplicates().sample(frac=1).reset_index(drop=True)

In [26]:
dataset.head(5)

,relation,head,tail
0,__label__Support,I accept what the president has said,the president and his experts have told Americ...
1,__label__Support,"He just -- he said, let it go bankrupt, period",I know he had no commitment to the automobile ...
2,__label__Support,He has voted against -- he voted including ano...,"He's been a maverick on some issues, but he ha..."
3,__label__Support,"Mine are words, and his was action","If you look at Bill Clinton, far worse"
4,__label__Support,he’s trying to conf–to scare people into think...,this is all about trying to dissuade people fr...

In [27]:
dataset.to_csv("/content/original_relations.tsv", sep="\t", index=False)